swagger: '2.0'
info:
  title: User Authentication and Data Retrieval API
  version: '1.0'
paths:
  /auth/register:
    post:
      summary: Register a new user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserRegistration'
      responses:
        201:
          description: User registered successfully
        500:
          description: Internal server error

  /auth/login:
    post:
      summary: Authenticate user and get JWT token
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserLogin'
      responses:
        200:
          description: JWT token generated successfully
        401:
          description: Invalid credentials
        500:
          description: Internal server error

  /data:
    get:
      summary: Fetch data from a public API
      parameters:
        - name: category
          in: query
          description: Category to filter the data
          required: false
          type: string
        - name: limit
          in: query
          description: Maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: Data fetched successfully
        500:
          description: Internal server error

definitions:
  UserRegistration:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
      password:
        type: string
        format: password

  UserLogin:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
        format: password
